// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Emotion = require("bs-emotion/src/Emotion.bs.js");

var button = Emotion.css(undefined, /* :: */[
      Emotion.label("button"),
      /* :: */[
        Emotion.color(/* `hex */[
              5194459,
              "e17a00"
            ]),
        /* :: */[
          Emotion.backgroundColor(/* `hex */[
                5194459,
                "2b3a5d"
              ]),
          /* :: */[
            Emotion.border(/* `px */[
                  25096,
                  0
                ], /* solid */12956715, /* `hex */[
                  5194459,
                  "e17a00"
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var Style = /* module */[/* button */button];

function Button(Props) {
  var handleClick = Props.handleClick;
  var children = Props.children;
  return React.createElement("button", {
              className: button,
              onClick: (function (_e) {
                  return Curry._1(handleClick, /* () */0);
                })
            }, children);
}

var make = Button;

exports.Style = Style;
exports.make = make;
/* button Not a pure module */
