// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Button = require("./Button.bs.js");
var UseCount = require("../UseCount.bs.js");

function Counter(Props) {
  var match = UseCount.useCount(/* () */0);
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Current Count: " + String(match[0])), React.createElement(Button.make, {
                  handleClick: match[1],
                  children: "Increment"
                }), React.createElement(Button.make, {
                  handleClick: match[2],
                  children: "Decrement"
                }), React.createElement(Button.make, {
                  handleClick: match[3],
                  children: "Reset"
                }));
}

var make = Counter;

exports.make = make;
/* react Not a pure module */
