// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Emotion = require("bs-emotion/src/Emotion.bs.js");

var wrapper = Emotion.css(undefined, /* :: */[
      Emotion.label("wrapper"),
      /* :: */[
        Emotion.display(/* flex */-1010954439),
        /* [] */0
      ]
    ]);

var Styles = /* module */[/* wrapper */wrapper];

function Task(Props) {
  var task = Props.task;
  var toggleTask = Props.toggleTask;
  return React.createElement("div", {
              className: wrapper
            }, React.createElement("h3", undefined, task[/* description */1]), React.createElement("input", {
                  type: "checkbox",
                  onClick: (function (_e) {
                      return Curry._1(toggleTask, task[/* id */0]);
                    })
                }));
}

var make = Task;

exports.Styles = Styles;
exports.make = make;
/* wrapper Not a pure module */
