// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function TaskInput(Props) {
  var handleSubmit = Props.handleSubmit;
  var match = React.useState((function () {
          return "";
        }));
  var setInput = match[1];
  var input = match[0];
  var internalSubmit = function (e) {
    e.preventDefault();
    Curry._1(handleSubmit, input);
    return Curry._1(setInput, (function (param) {
                  return "";
                }));
  };
  var internalChange = function (e) {
    var newInput = e.target.value;
    return Curry._1(setInput, (function (param) {
                  return newInput;
                }));
  };
  return React.createElement(React.Fragment, undefined, React.createElement("form", {
                  onSubmit: internalSubmit
                }, React.createElement("label", {
                      htmlFor: "task-input"
                    }, "Enter a task"), React.createElement("input", {
                      id: "task-input",
                      name: "task",
                      value: input,
                      onChange: internalChange
                    }), React.createElement("button", {
                      type: "submit"
                    }, "Submit")));
}

var make = TaskInput;

exports.make = make;
/* react Not a pure module */
