// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Blah(Props) {
  var something = Props.something;
  var children = Props.children;
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, something), React.createElement("p", undefined, children));
}

var make = Blah;

exports.make = make;
/* react Not a pure module */
