// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function Link(Props) {
  var href = Props.href;
  var text = Props.text;
  return React.createElement(React.Fragment, undefined, React.createElement("a", {
                  href: href,
                  onClick: (function (e) {
                      var href$1 = href;
                      var $$event = e;
                      if ($$event.defaultPrevented) {
                        return 0;
                      } else {
                        $$event.preventDefault();
                        return ReasonReactRouter.push(href$1);
                      }
                    })
                }, text));
}

var make = Link;

exports.make = make;
/* react Not a pure module */
