// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Task = require("../components/Task.bs.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");

function AllTasks(Props) {
  var tasks = Props.tasks;
  var toggleTask = Props.toggleTask;
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Tasks"), $$Array.of_list(List.map((function (t) {
                        return React.createElement(Task.make, {
                                    task: t,
                                    toggleTask: toggleTask,
                                    key: t[/* id */0]
                                  });
                      }), tasks)));
}

var make = AllTasks;

exports.make = make;
/* Task Not a pure module */
