// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Home(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Hello"));
}

var make = Home;

exports.make = make;
/* react Not a pure module */
