// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function NotFound(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("p", undefined, "Sorry, that page doesn't exist"));
}

var make = NotFound;

exports.make = make;
/* react Not a pure module */
