// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function TaskPage(Props) {
  var id = Props.id;
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Task id: " + id));
}

var make = TaskPage;

exports.make = make;
/* react Not a pure module */
