// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var App = require("./App.bs.js");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");

ReactDOMRe.renderToElementWithId(React.createElement(App.make, {
          name: "Matt"
        }), "app");

/*  Not a pure module */
