// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function useCount(param) {
  var match = React.useState((function () {
          return 0;
        }));
  var setCount = match[1];
  var inc = function (param) {
    return Curry._1(setCount, (function (c) {
                  return c + 1 | 0;
                }));
  };
  var dec = function (param) {
    return Curry._1(setCount, (function (c) {
                  return c - 1 | 0;
                }));
  };
  var reset = function (param) {
    return Curry._1(setCount, (function (param) {
                  return 0;
                }));
  };
  return /* tuple */[
          match[0],
          inc,
          dec,
          reset
        ];
}

exports.useCount = useCount;
/* react Not a pure module */
